name: joes-book
services:
  db:
    container_name: joes-db
    image: mongo:latest
    volumes:
      - ./db_data:/data/db
    restart: always
    # Uncomment to create secure root user (joes-book MONGO_URI env var must reflect this)
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=Admin
    #   - MONGO_INITDB_ROOT_PASSWORD=changeme

    # Uncomment to expose db on host port
    # ports:
      # - 27017:27017

  joes-book:
    container_name: joes-webapp
    image: ghcr.io/aldenmoreton/joes-book:latest
    ports:
      - 3000:3000
    restart: always
    environment:
      - MONGODB_URI=mongodb://joes-db:27017/app # Must reflect db env vars

      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}

      - GITHUB_ID=${GITHUB_ID}
      - GITHUB_SECRET=${GITHUB_SECRET}

    depends_on:
      - db
